version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3001:3001"
