# Use an official Node runtime as a parent image
FROM node:alpine as build

WORKDIR /app

COPY ./lychee-outro-client/package*.json ./

RUN npm install

COPY ./lychee-outro-client .

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
